webPass/Models/PassParameterDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace webPass.Models
{
    public class PassParameterDto
    {
        [Display(Name = "Web Site or App Name\n(example: www.sitename.com)")]
        public string webSiteName { get; set; }
        [Display(Name = "User Name or Email Address\n(example: user@mail.com)")]
        public string userName { get; set; }
        [Display(Name = "Key value\n(remember it!)")]
        public string keyValue { get; set; }
        [Display(Name = "Length of generated password\n(default 8)")]
        [Required(ErrorMessage = "Length of generated password is required")]
        public int lengthOfPassword { get; set; }
        [Display(Name = "Use Special Character")]
        public bool useSpecialCharacter { get; set; }
    }
}

webPass/Controllers/PassGenController.cs
using CaptchaMvc.HtmlHelpers;
using PasswordGenerator;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webPass.Models;

namespace webPass.Controllers
{
    public class PassGenController : Controller
    {

        // GET: PassGen/Create
        public ActionResult Create()
        {
            PassParameterDto model = new PassParameterDto()
            {
                lengthOfPassword = 8,
                useSpecialCharacter = true
            };
            return View(model);
        }

        // POST: PassGen/Create
        [HttpPost]
        public ActionResult Create(PassParameterDto model)
        {
            try
            {
                if (!this.IsCaptchaValid("Validate your captcha"))
                {
                    throw new Exception( "Invalid Captcha");
                }
                if (model == null || !ModelState.IsValid)
                {
                    throw new HttpException(System.Net.HttpStatusCode.BadRequest.ToString());
                }

                Parameters parameter = new Parameters()
                {
                    keyValue = model.keyValue == null ? "" : model.keyValue.Trim().ToLower(),
                    lengthOfPassword = model.lengthOfPassword,
                    userName = model.userName == null ? "": model.userName.Trim().ToLower(),
                    useSpecialCharacter = model.useSpecialCharacter,
                    webSiteName = model.webSiteName==null?"":model.webSiteName.Trim().ToLower()
                };

                string password = PassMaker.GetPassword(parameter);


                ViewBag.Password = password;

                return View();
            }
            catch (Exception x)
            {
                string error = "";
                while (x != null)
                {
                    error += x.Message;
                    x = x.InnerException;
                }
                ViewBag.Error = error;
                return View(model);
            }
        }
    }
}

webPass/Views/PassGen/Create.cshtml
@model webPass.Models.PassParameterDto
@using CaptchaMvc.HtmlHelpers
@{
    ViewBag.Title = "Create";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>

@if (@ViewBag.Password != null)
{
    <br />
    <label class="control-label col-md-2" for="generatedPass">Created Password</label>
    <input type="text" value="@ViewBag.Password" id="generatedPass">
    <button onclick="copyText()">Click to copy</button>
}
else
{
    <h2>Generate password</h2>
}

@if (@ViewBag.Error != null)
{
    <h4><font color="red"> Failed with message: @ViewBag.Error </font></h4>
}
    


@using (Html.BeginForm(null, null, FormMethod.Post, new { name = "frm", id = "frm" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">


        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.webSiteName, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.webSiteName, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.webSiteName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.keyValue, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.keyValue, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.keyValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lengthOfPassword, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.lengthOfPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lengthOfPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.useSpecialCharacter, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                <div class="checkbox">
                    @Html.EditorFor(model => model.useSpecialCharacter)
                    @Html.ValidationMessageFor(model => model.useSpecialCharacter, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-3" for="Captcha">Please enter Captcha</label>
            <div class="col-md-9">
                    @*@Html.MathCaptcha()*@
                    @Html.Captcha(1)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    function copyText() {
      /* Get the text field */
      var copyText = document.getElementById("generatedPass");

      /* Select the text field */
      copyText.select();
      copyText.setSelectionRange(0, 99999); /*For mobile devices*/

      /* Copy the text inside the text field */
      document.execCommand("copy");
    }

    //$('input[type=submit]').click(function () {
    //    var clickedBtn = $(this)
    //     clickedBtn.hide(100);
    //});

    $(document).ready(function () {
        //$("frm :input").attr("autocomplete", "off");
         $('input[type=submit]').show(100);

        $("form").submit(function(e) {
            //e.preventDefault();
            // rest code goes here
            clickedBtn.hide(100);
        });
    });
</script>

webPass/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="~/Content/MultiLineLabel.css" rel="stylesheet" />
    <title>@ViewBag.Title - Password Hash</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Password Generator", "Create", "PassGen", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Generate Password", "Create", "PassGen")</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Password Generator</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>